<a href="https://colab.research.google.com/github/KonradCe08/kurs_SDA/blob/main/notatnika_statystyka_prawdopodobienstwo_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Zadanie 1


Stwórz numpy array z wartościami od 1 do doss 9, wyświetl, a następnie odwróć tę tablicę (pierwszy element zostaje ostatnim, itd.). 

In [ ]:
import numpy as np
a=np.arange(1,10)
print(a)
print(a[2])
print(a[::-1])
a1=a[::-1]
a1
a*a1

[1 2 3 4 5 6 7 8 9]
3
[9 8 7 6 5 4 3 2 1]


array([ 9, 16, 21, 24, 25, 24, 21, 16,  9])

### Zadanie 2

Stwórz następujący numpy array: [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]; a następnie wypisz wszystkie unikalne (nie powtarzające się) elementy.

In [ ]:
import numpy as np
a=np.array([1,23,4,31,1,1,4,23,4,1])
print(a)
a=np.unique(a)
print(a)
print(a.shape)
print(a.ndim)
type(a)

[ 1 23  4 31  1  1  4 23  4  1]
[ 1  4 23 31]
(4,)
1


numpy.ndarray

### Zadanie 3

Stwórz macierz 3x3 (używając reshape) z wartościami od 2 do 10.

In [ ]:
a=np.arange(2,11)
print(a)
a1=a.reshape(3,3)
a2=a1.T
print(a1)
print(a2)
np.add(a1,a2)+5

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]


array([[ 9, 13, 17],
       [13, 17, 21],
       [17, 21, 25]])

### Zadanie 4

Stwórz tablicę z sześcioma losowymi wartościami z przedziału od 10 do 30.

In [ ]:
a=np.random.randint(1,31,size=6)
print(a)
sorted(a)
np.unique(a)

np.median(np.unique(a))

[ 6 16  4  6 16  3]


5.0

### Zadanie 5

Spośród tablicy wartości: [23, 45, 112, 150, 43, 254, 95, 8] wyfiltruj te, które są większe od 100.

In [ ]:
a=np.array([23, 45, 112, 150, 43, 254, 95, 8])
print(type(a))
wiecej_sto=np.where(a>100,100,a)
print(wiecej_sto)
#a[wiecej_sto[0]]
type(wiecej_sto)
wiecej_sto.ndim
print('srednia:'+str(np.mean(wiecej_sto)))
print('mediana:'+str(np.median(wiecej_sto)))
print('roznica miedzy srednia a mediana'+str(np.mean(wiecej_sto)-np.median(wiecej_sto)))

<class 'numpy.ndarray'>
[ 23  45 100 100  43 100  95   8]
srednia:64.25
mediana:70.0
roznica miedzy srednia a mediana-5.75


### Zadanie 6

Stwórz poniższą macierz 4x4, a następnie:
* wyświetl element z drugiego wiersza i trzeciej kolumny, 
* oblicz jej wyznacznik,
* oblicz jej ślad (sumę elementów na głównej przekątnej),
* znajdź element największy i najmniejszy.

$ \begin{bmatrix}
1 & 15 & 4 & 13 \\
8 & 21 & 3 & 12 \\
11 & 13 & 11 & 5 \\
32 & 13 & 0 & 2 
\end{bmatrix}  $

In [ ]:
a=np.array([[1,15,4,13],[8,21,3,12],[11,13,11,5],[32,13,0,2]])
print(a[1,2])
print('element:'+str(a[1,2]))
print(np.linalg.det(a))
a.diagonal().sum()
a.min()
a.max()

3
element:3
-19963.99999999999


32

### Zadanie 7



Stwórz dowolną tablicę wartości, a następnie oblicz średnią i medianę.

In [ ]:

a=np.array([10.5,13,3.16,21,33.5])
print(a)
print(median(a))
print(mean(a))

[10.5  13.    3.16 21.   33.5 ]
13.0
16.232


### Zadanie 8

Stwórz dowolną tablicę wartości, a następnie je znormalizuj - tj. od każdego elementu tablicy odejmij średnią i podziel przez odchylenie standardowe.

In [ ]:
a=np.array([10.5,13,3.16,21,33.5])
m1=np.mean(a)
s1=np.std(a)
a1=a-m1
a2=a1/s1
m2=np.mean(a2)
s2=np.std(a2)
print(a1)
print(a2)
print(m2)
print(s2)

[ -5.732  -3.232 -13.072   4.768  17.268]
[-0.5540834  -0.31242106 -1.26360401  0.4608984   1.66921007]
0.0
1.0


### Zadanie 9

Stwórz funkcję, która przyjmuje dwa wektory (oba o tym samym wymiarze) w postaci numpy tablicy, a zwróci odległość euklidesową między nimi.

 $ d\left( p,q\right)   = \sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } $

### Zadanie 10

Korzystając z testu Shapiro-Wilka sprawdź, czy podana próba ma rozkład normalny: [0.873, 2.817, 0.121, -0.945, -0.055, -1.436, 0.360, -1.478, -1.637, -1.869] 
